version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "443:8443"
  #   depends_on:
  #     - db
  #   environment:
  #     - "PGADMIN_DEFAULT_PASSWORD=postgres"

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  web:
    build: .
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "4000:4000"
    depends_on:
      - db
